server:
  port: ${app.port}

spring:
  cloud:
    gateway:
      routes:
        - id: movies_service
          uri: lb://${app.movies-service}
          predicates:
            - Path=/api/v1/movies/**
          filters:
            - AddRequestHeader=X-Request-AppId, Api-Gateway
        - id: actors_service
          uri: lb://${app.actors-service}
          predicates:
            - Path=/api/v1/actors/**
          filters:
            - AddRequestHeader=X-Request-AppId, Api-Gateway
      discovery:
        locator:
          enabled: true
  zipkin:
    enabled: ${ZIPKIN_ENABLED:false}
    base-url: ${ZIPKIN_URL:http://localhost:9411/}
