server:
  port: ${app.port}

spring:
  cloud:
    gateway:
      routes:
        - id: movies_service
          uri: lb://${app.movies-service}
          predicates:
            - Path=/api/v1/movies/**
          filters:
            - AddRequestHeader=X-Request-AppId, Api-Gateway
            - RemoveRequestHeader=Cookie
        - id: actors_service
          uri: lb://${app.actors-service}
          predicates:
            - Path=/api/v1/actors/**
          filters:
            - AddRequestHeader=X-Request-AppId, Api-Gateway
            - RemoveRequestHeader=Cookie
      discovery:
        locator:
          enabled: true
  zipkin:
    enabled: ${app.zipkin.enabled}
    base-url: ${app.zipkin.url}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.auth.issuer-uri}


