server:
  port: ${app.port}

spring:
  main:
    allow-bean-definition-overriding: true
  zipkin:
    enabled: ${app.zipkin.enabled}
    base-url: ${app.zipkin.url}

#Swagger properties
springdoc:
  swagger-ui:
    path: /
    enabled: ${app.allow-swagger}
  api-docs:
    path: /v3/api-docs
    enabled: ${app.allow-swagger}

#Mongo migrations
mongock:
  enabled: true
  migration-scan-package: org.example.actorsapi.infrastructure.migrations

#App properties
app:
  security:
    ignore-paths: /swagger/**,/v3/api-docs/**
  messaging:
    exchange-name: movies-topic
    exchange-type: topic
    routing-key: movie.like
    queue-name: movies-topic.${spring.application.name}



