server:
  port: ${app.port}

spring:
  application:
    name: actors-api
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      function:
        definition: likeListener
      bindings:
        likeListener-in-0:
          destination: movies-topic
          group: ${spring.application.name}
          consumer:
            concurrency: 5
      rabbit:
        bindings:
          likeListener-in-0:
            consumer:
              bindingRoutingKey: movie.like

#Swagger properties
springdoc:
  swagger-ui:
    path: /
    enabled: ${app.allow-swagger}
  api-docs:
    path: /v3/api-docs
    enabled: ${app.allow-swagger}

#Mongo migrations
mongock:
  enabled: true
  migration-scan-package: org.example.actorsapi.infrastructure.migrations

#Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${app.eureka.username}:${app.eureka.password}@${app.eureka.host}:${app.eureka.port}/eureka

spring.cloud.discovery.enabled: true

#App properties
app:
  security:
    ignore-paths: /swagger/**,/v3/api-docs/**




