server.port: ${EUREKA_PORT:8761}

eureka.client:
  register-with-eureka: false
  fetch-registry: false
  service-url:
    defaultZone: ${EUREKA_URL:http://myuser:mypass@localhost:8761/eureka}

spring:
  security:
    user:
      name: ${EUREKA_USERNAME:myuser}
      password: ${EUREKA_PASSWORD:mypass}
  application:
    name: eureka-server

