server:
  port: ${app.config.port}

spring:
  application:
    name: config-server
  security:
    user:
      name: ${app.config.username}
      password: ${app.config.password}
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/carlosggz/config-server-demo
          searchPaths: .,{application}
          clone-on-start: true

#Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${app.eureka.url}

#Encryption properties
encrypt:
  key: MySuperSecretKey
  salt: abcdef

