server:
  port: ${CONFIG_PORT:8084}

spring:
  application:
    name: config-server
  security:
    user:
      name: ${CONFIG_USERNAME:ConfigUser}
      password: ${CONFIG_PASSWORD:ConfigPassword}
  cloud:
    discovery:
      enabled: true
    config:
      server:
        git:
          uri: https://github.com/carlosggz/config-server-demo
          searchPaths: .,{application}

#Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://myuser:mypass@localhost:8761/eureka}
