version: '3.4'

services:
  postgres:
    image: postgres:13.7
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: postgres
    networks:
      - my-network
  rabbitmq:
    image: rabbitmq:3.8.5-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: mypass
    networks:
      - my-network
  mongo:
    image: mongo:5.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypass
    ports:
      - "27017:27017"
    networks:
      - my-network
  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
    networks:
      - my-network
  auth:
    image: quay.io/keycloak/keycloak:18.0
    container_name: keycloack-auth
    ports:
      - "9000:8080"
    environment:
      KEYCLOAK_ADMIN: myuser
      KEYCLOAK_ADMIN_PASSWORD: mypass
    command:
      - start-dev
      - --import-realm
    volumes:
      - ../auth/realm.json:/opt/keycloak/data/import/realm.json
      - ../auth/add-user.sh:/opt/add-user.sh
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
