server:
  port: ${app.port}

spring:
  application:
    name: movies-api
  cloud:
    stream:
      bindings:
        like-out-0:
          destination: movies-topic
          content-type: application/json
          binder: rabbit
      rabbit:
        bindings:
          like-out-0:
            producer:
              routing-key-expression: headers.myRoutingKey

#Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://${app.eureka.username}:${app.eureka.password}@${app.eureka.host}:${app.eureka.port}/eureka

spring.cloud.discovery.enabled: true

#Swagger properties
springdoc:
  swagger-ui:
    path: /
    enabled: ${app.allow-swagger}
  api-docs:
    path: /v3/api-docs
    enabled: ${app.allow-swagger}

#App properties
app:
  security:
    ignore-paths: /swagger/**,/v3/api-docs/**
