spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: myuser
    password: mypass
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    sql-migration-prefix: V
    table: schema_version
    schemas: movies_schema
    init-sqls: CREATE SCHEMA IF NOT EXISTS movies_schema;
    fail-on-missing-locations: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: movies_schema
  rabbitmq:
    username: myuser
    password: mypass
    host: localhost
    port: 5672
    virtual-host: /

app:
  port: 8081
  allow-swagger: true
  eureka:
    host: localhost
    port: 8761
    username: myuser
    password: mypass
